name: Deploy to AWS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest  # Runs on GitHub-hosted VM
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install AWS CLI  # Ensures AWS CLI is installed
        run: |
          sudo apt update
          sudo apt install -y awscli

      - name: Verify AWS CLI installation
        run: aws --version  # Should print the installed AWS CLI version

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1  # Change this to your AWS region

      - name: List S3 Buckets (Test Command)
        run: aws s3 ls  # Checks if AWS CLI is working
